### ISSUE TITLE
View/Save as RelaxNG

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/sensorml-editor#14]
Was trying to experiment with using the editor to create the beginnings of a RelaxNG profile, but "view as RelaxNG" didn't work. Should prove useful for that, particularly as the editor interface improves.

**Comment by mikebotts** [comment]
Ironically, the editor shows the RelaxNG if I load an XML encoded SensorML description, but it doesn't display the RelaxNG if I'm using the editor to create the XML.

Works:
http://mdhsl.github.io/SMLEditor/SensorMLEditor.html?url=http%3A%2F%2Fwww.sensorML.com%2F2.0%2Fmvco%2Fsensor%2FMVCO_Workhorse_1200.xml

**Comment by mikebotts** [comment]
Being able to go from XML to RelaxNG does allow me to use existing SensorML descriptions to create RelaxNG profiles, which I think will be useful, but I need to consider the differences between doing that relative to creating RelaxNG using the editor.

**Comment by mdhsl** [comment]
The relaxNG can be visualized now but only user input and current state can be viewed. That means for example for a ZeroOrMore element, you can only view the ZeroOrMore element which have been added (patterns) and not the source itself
