### ISSUE TITLE
Classification title not showing

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/sensorml-editor#15]
When one adds an IdentificationList, the "Identification" title shows next to the X. This doesn't happen when a ClassifierList is added.

**Comment by mikebotts** [comment]
Additional info regarding this Issue. Before one adds a label to an IdentifierList or ClassificationList, the titles "Identification" and "Classification" show up. However, after one adds a Label, then the titles "Identification" and "Classification" disappear and are replaced by the Label.

The titles "Identification" and "Classification" should remain to identify the information type in that section, but with the Label being shown below the title or in parenthesis to the right.

**Comment by mdhsl** [comment]
I think it's better to replace the "Identification" and "Classification" if one uses a label instead. Indeed, in that way the user can choose to keep or replace the "Identifcation" name by everything he wants.
For example, if he wants to keep Identification and put a label in parenthesis like Classification(CustomLabel) or if he wants to replace the whole title like CustomeLabel he can do it.
If we let as default name Classification/Identification and he does not want, that restricts the user choice.

**Comment by mdhsl** [comment]
done as requested
