### ISSUE TITLE
Label shows twice in "Edit inputs" window, then changes to "description"

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/sensorml-editor#18]
When editing inputs (i.e. SWE Common data types), "label" shows up twice. However, if one adds the second "label" it becomes "description".

![screen shot 2017-01-13 at 4 06 06 pm](https://cloud.githubusercontent.com/assets/7469574/21947335/44432a00-d9aa-11e6-87d6-93d62915a013.jpg)

![screen shot 2017-01-13 at 4 06 20 pm](https://cloud.githubusercontent.com/assets/7469574/21947342/5394dfd0-d9aa-11e6-936d-5222d5512228.jpg)

**Comment by mdhsl** [comment]
This is a wrong typing into the swe/simpleTypes.rng
I tried to push the change but it does not work. Do I have the correct right to write into the repo?
Anyway, the fix is to replace (swe/simpleTypes.rng):

```xml
<define name="swe.description">
      <a:documentation>label</a:documentation>
      <element name="swe:description">
         <data type="string">
            <param name="minLength">1</param>
         </data>
      </element>
   </define>
```

into 
```xml
<define name="swe.description">
      <a:documentation>description</a:documentation>
      <element name="swe:description">
         <data type="string">
            <param name="minLength">1</param>
         </data>
      </element>
   </define>
```

**Comment by mikebotts** [comment]
We may be working off of different repositories. I hope the one I’m working on is the latest since I’m using it to create profiles and such. Its one that Alex, made some simplification mods. 

It’s taking me awhile to decide how I’m going to handle things but right now I’m creating a basic_sml folder with simplified and basic SensorML properties … this is removing a lot of the choices where appropriate and simplifying other things. I should have this ready in a day or two. I will need to be able to point to it in the Editor.

I’m also creating some profiles, like simple_deployment, etc.

You and I and Alex should Hangout this week.

Dr. Mike Botts
Botts Innovative Research, Inc.
http://www.botts-inc.com
http://opensensorhub.org
mike.botts@botts-inc.com
