### ISSUE TITLE
Bring Ontology Search capabilities back into editor

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/sensorml-editor#20]
We previously had the ability to search an ontology for terms and them select. Previously this was done by downloading the ontology and doing a search directly on the "local" version. This search however, can be done by using the search capabilities on the Ontology (ORR) web services.

For example, see: http://sensorml.com/orr/#st

This search can also be done using sparQL:  http://sensorml.com/ont/sparql.html

**Comment by mdhsl** [comment]
The local search is working but we can also use the search tool using sparQL or WS. This is an enhancement

**Comment by mikebotts** [comment]
Nope, this is a requirement  :)

The current window BTW, seems to only get a few of the matches but not all, plus the window cannot be expanded in the horizontal direction to read the description of the term.
