### ISSUE TITLE
DataRecord not displaying correctly

### ISSUE THREAD

**Issue by mikebotts** [opensensorhub/sensorml-editor#31]
DataRecord display is missing two behaviors:
1. replace "DataRecord" with <Label> value or <field> name attribute if it exist
2. indent the fields

See below for current:

![screen shot 2017-07-19 at 3 46 49 pm](https://user-images.githubusercontent.com/7469574/28388836-99e1221e-6c99-11e7-8e35-e8ff67f7c3d6.jpg)

**Comment by alexrobin** [comment]
This was due to an error in the RelaxNG profile
